### ISSUE TITLE
How to configure with a Github token

### ISSUE THREAD

**Issue by mcollina** [fastify/gh-issues-finder#129]
From https://github.com/mercurius-js/mercurius/issues/941#issuecomment-1399230693: 

> If it is configured with a GH token, which the app source supports, then we shouldn't be rate limited (on any org, not just fastify), but since we are, it feels like the app is running without a GH token.

@simoneb how do I configure this with a token?

**Comment by simoneb** [comment]
@syedfarhanNF can you please look into this? It requires changing the workflow to pass the env var for the token, populated from the gh secret called GH_AUTH_TOKEN

**Comment by syedfarhanNF** [comment]
You will need to create a new secret if doesn't already exist called GH_AUTH_TOKEN. Then modify the github workflow for deployment so it passes this secret into the containers environment variables.

```
id: 'deploy'
  uses: google-github-actions/deploy-cloudrun@v1
  with:
    service: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }}
    region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
    project_id: ${{ secrets.GCP_PROJECT_ID }}
    flags: --allow-unauthenticated --timeout 1800
    env_vars: |
    GH_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
    source: .
```
